engines:
  - name: "openai-gpt4"
    engine: "openai"
    model: "gpt-4"
    api_key: "${OPENAI_API_KEY}"
    max_tokens: 2000
    temperature: 0.7

  - name: "anthropic-claude"
    engine: "anthropic"
    model: "claude-3-sonnet-20240229"
    api_key: "${ANTHROPIC_API_KEY}"
    max_tokens: 2000
    temperature: 0.7

  - name: "google-gemini"
    engine: "google"
    model: "gemini-pro"
    api_key: "${GOOGLE_API_KEY}"
    max_tokens: 2000
    temperature: 0.7
