[package]
name = "fluent-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
fluent-engines = { workspace = true }
fluent-core = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
clap = { workspace = true }

